# Generated by Django 5.0.7 on 2024-07-16 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='media/publisher/icons')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2083)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='blog.article')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='blog.publisher')),
            ],
        ),
    ]
