# Generated by Django 4.2.7 on 2024-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_ventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='link',
            field=models.CharField(default='link not filled in', max_length=2083),
        ),
    ]
