# Generated by Django 4.2.7 on 2024-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='views',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
